AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'examples/**/*'

plugins:
  - rubocop-rake

require:
  - rubocop-rspec

# Disable problematic cops that cause errors
Capybara/RSpec/PredicateMatcher:
  Enabled: false

# Layout rules
Layout/LineLength:
  Max: 120
  Exclude:
    - 'gasfree_sdk.gemspec'
    - 'examples/**/*'

# Metrics rules
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

Metrics/MethodLength:
  Max: 17
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

# Documentation rules
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - 'lib/gasfree_sdk/errors.rb'

# RSpec rules
RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Max: 15

# String literal rules
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Disable some overly strict cops for this project
Style/FrozenStringLiteralComment:
  Enabled: true

# Gemspec rules - be more lenient for development gems
Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
